#!/usr/bin/env python3
"""Bind locally generated model registries to an inference protocol."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Mapping

from nontransitive_safety.provenance import canonical_json_bytes, sha256_file

REPO = Path(__file__).resolve().parents[1]


def _load_object(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"JSON object required: {path}")
    return value


def _relative_to_repo(path: Path) -> str:
    try:
        return path.resolve().relative_to(REPO.resolve()).as_posix()
    except ValueError as error:
        raise ValueError(
            "model registries must be stored inside the release repository"
        ) from error


def _refresh_file_hashes(value: Any) -> None:
    if isinstance(value, dict):
        path_value = value.get("path")
        if isinstance(path_value, str) and "sha256" in value:
            candidate = Path(path_value)
            if not candidate.is_absolute() and (REPO / candidate).is_file():
                value["sha256"] = sha256_file(REPO / candidate)
        for child in value.values():
            _refresh_file_hashes(child)
    elif isinstance(value, list):
        for child in value:
            _refresh_file_hashes(child)


def _write(path: Path, value: Mapping[str, Any]) -> None:
    payload = canonical_json_bytes(value) + b"\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(payload)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--protocol", type=Path, required=True)
    parser.add_argument(
        "--registry",
        type=Path,
        action="append",
        required=True,
        help="Frozen registry generated by build_local_hf_registry.py. Repeat as needed.",
    )
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--refresh-config",
        type=Path,
        action="append",
        default=[],
        help="Also refresh repository-relative path hashes in another JSON config.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    protocol = _load_object(args.protocol.resolve())
    bindings = {}
    for registry_path in args.registry:
        resolved = registry_path.resolve()
        registry = _load_object(resolved)
        snapshot_id = registry.get("candidate_snapshot_id")
        if not isinstance(snapshot_id, str) or not snapshot_id:
            raise ValueError(f"candidate_snapshot_id is absent: {resolved}")
        if snapshot_id in bindings:
            raise ValueError(f"duplicate registry for {snapshot_id}")
        bindings[snapshot_id] = {
            "path": _relative_to_repo(resolved),
            "sha256": sha256_file(resolved),
        }
    protocol["model_registries"] = dict(sorted(bindings.items()))
    output = args.output.resolve()
    _write(output, protocol)
    print(f"Bound {len(bindings)} model registries in {output}")

    for config_path in args.refresh_config:
        resolved = config_path.resolve()
        config = _load_object(resolved)
        _refresh_file_hashes(config)
        _write(resolved, config)
        print(f"Refreshed repository-relative hashes in {resolved}")


if __name__ == "__main__":
    main()
